# List all worker node names on your private network.

# worker node 1
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  labels:
    ibm.role: worker_private
  # run ibmcloud ks workers <cluster-name> to see worker node name and private IP
  name: <worker-node-name>-worker-private
spec:
  node: <worker-node-name>.cloud.ibm
  # Interface name for virtual machines on the private network.
  interfaceName: eth0
  # Worker node private IP
  expectedIPs:
  - <worker-node-private-ip>
    
---
  
# worker node 2
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  labels:
    ibm.role: worker_private
  # run ibmcloud ks workers <cluster-name> to see worker node name and private IP
  name: <worker-node-name>-worker-private
spec:
  node: <worker-node-name>.cloud.ibm
  # Interface name for virtual machines on the private network.
  interfaceName: eth0
  # Worker node private IP
  expectedIPs:
  - <worker-node-private-ip>
  
# If you have additional worker nodes, copy the above hostEndpoint and fill in appropriate values.
