apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs-bot
  template:
    metadata:
      labels:
        app: cs-bot
    spec:
      containers:
      - image: <image_repo>
        name: cs-bot
      restartPolicy: Always
