# This policy opens port 10250 for VPN communication between master and workers, the DNS port
# (53), port 2049 for communication with NFS file servers, ports 443 and 3260 for communication
# to block storage, port 2040 for the master API server local proxy, and port 2041 for the
# etcd local proxy.

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-master-local-public
spec:
  egress:
  - action: Allow
    destination:
      nets:
      - 172.20.0.1/32
      - 172.21.0.1/32
      ports:
      - 53
      - 2049
      - 443
      - 3260
      - 2040
      - 2041
    protocol: UDP
    source: {}
  - action: Allow
    destination:
      nets:
      - 172.20.0.1/32
      - 172.21.0.1/32
      ports:
      - 53
      - 2049
      - 3260
      - 443
      - 2040
      - 2041
    protocol: TCP
    source: {}
  ingress:
  - action: Allow
    destination:
      ports:
      - 53
      - 10250
    protocol: UDP
    source: {}
  - action: Allow
    destination:
      ports:
      - 53
      - 10250
    protocol: TCP
    source: {}
  order: 1500
  selector: ibm.role == 'worker_public'
  types:
  - Ingress
  - Egress
